### ISSUE TITLE
Version for CS2

### ISSUE THREAD

**Issue by isvktt** [kaisersoju/WindMouse#1]
Could you make a version that works on cs2, that would be really good, thanks for sharing your code. I have greater knowledge of Python, do you have the Python code?

**Comment by kaisersoju** [comment]
The code here is universal to any project that requires human-like mouse movement in either absolute or relative coordinates. ChatGPT didn't make this specifically for CSGO or CS2. As you can see, the code doesn't have any aimbot or mouse movement function implemented. I'd recommend you find a good source code that does those things well and add wind_mouse. In my case, I used ekknod's EC base if you're comfortable enough with c++ as your programming language.

Please check the link in this repo's readme for the original python version that the c version is directly based on. It's quite easy to understand this code. Note also that the python example is for absolute coordinates which isn't ideal for FPS games with a crosshair like it is for CS2. It's easier to use the relative vector X, Y values instead. I'm not aware of any good python base to recommend that handles mouse or aiming other than another of ekknod's project called scripthial.

edit: EC has some early stage untested CS2 code but UNTESTED. There isn't full working python code I'm aware of that works with CS2 yet.

**Comment by isvktt** [comment]
I understand, if you can share a code with aim using this human movement I would appreciate it, I have greater knowledge in python, I would use it for knowledge and implement it in CS2 using python

**Comment by kaisersoju** [comment]
[https://github.com/ekknod/EC/blob/main/cs2/shared/features.cpp#L353](url)

I don't have plans to do CS2 at the moment, but there's little difference with EC-CSGO. I'd replace the line linked above with wind_mouse and make sure the function is returning relative coordinates instead of absolute coordinates. I'd also remove the smoothing since wind_mouse is meant to replace it with it's own built in human-like movement.

I'm really not sure how sharing c++ code will help you. Wouldn't finding python source code for CS2 be better for you since you understand that language? You can update scripthial to work on CS2.

[https://github.com/ekknod/scripthial](url)

**Comment by isvktt** [comment]
I understood, I thought you would provide the source of your example that you made for CSGO, I would adapt it for my CS2 project using my memory reading, thanks for the information, I will study more on the subject

**Comment by isvktt** [comment]
Another question, which type of aimbot do you currently consider the safest to use in VAC? Can you tell me briefly about, I'm starting a project and I'm studying a lot about the best and safest way to implement an aim that remains undetectable for a long time

**Comment by kaisersoju** [comment]
CS2 is a newer game with not enough precedent for how VACNET detects aimbots so everyone's prior knowledge based on CSGO and VAC will be flawed or limited.

We know it uses machine learning and collects data of what happened before hitting/missing a target until a little bit afterwards. It used CSGO overwatch cases to learn and probably other sources. Because VAC lately seemed to have a poor record of detecting sometimes the most obvious rage aimbot settings, maybe it's goal was training VACNET with a larger dataset coming from both cheaters and legitimate players to obtain a higher certainty someone's aim was human or machine. Only Valve would know what weights were used and what got adjusted over time to accomplish better aimbot detection with VACNET. So far, it is too early to say how reliable this is as we don't see many examples of VAC Live yet. Valve tends to do these sorts of things very slowly anyway. What works as an aimbot today may not later. Plus cheat detection and prevention looks a many factors including statistics and profiling the cheaters themselves. My view is all aimbots are unsafe as their usage almost always garners reports by other players. Bad players with poor game knowledge but with "pro level" aim is above suspicious. Valve is pressured to deliver a better experience in CS2 and removing the most egregious cheaters would be the lowest hanging fruit to win big on. Closet cheaters and smurfs on the other hand are most likely more complex problems to solve as it only affects very few people playing at higher competitive levels. That's the "safety zone" for aimbots.

The better your human aim is the more machine-like or consistent-like it becomes is the counterargument. Since that goal is not sustainable for bio-mechanical reasons, your aimbot must achieve that fine balance of being consistent enough to give you an edge but also fall short enough to show some human imprecision. That means sometimes your aimbot under or over aims before correcting it. Will this beat future VACNET? Who knows.
